Filter out automated commits
EmesaDEV/actions pull request #33
Opened 2023-10-10 13:23 UTC by akaRem

It could be nicer to filter commits based on bot name, but then we need to reconfigure these pipelines everywhere to pass bot name.

But we have a convention to prefix `[AUTOMATED]` commits.. Which should work as well..

2023-10-10 13:24 UTC, akaRem commented
Please review with ignored whitespace changes.

2023-10-12 08:08 UTC, guilhermeassad requested changes
Please check my comment.

2023-10-12 08:42 UTC, akaRem commented on .github/workflows/terraform-detect-drift-full-reusable.yml
> +          last_commit="$(git log --pretty=format:"%an <%ae> - %cd - %s" --date=short | grep -vi ' - \[AUTOMATED\] ' | head -1)"
Fixed

2023-10-12 08:49 UTC, guilhermeassad approved these changes
Looks good

2023-10-12 08:58 UTC, merged